# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 11:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaBio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('age', models.IntegerField()),
                ('country', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='BioEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('living_space', models.IntegerField()),
                ('number_of_people', models.IntegerField()),
                ('year_from', models.IntegerField()),
                ('year_to', models.IntegerField()),
                ('area_bio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='areas.AreaBio')),
            ],
        ),
    ]
