# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 08:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bioentry',
            options={'ordering': ['year_from']},
        ),
        migrations.AlterModelManagers(
            name='areabio',
            managers=[
                ('data', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='areabio',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
