# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0002_auto_20170218_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='bioentry',
            name='description',
            field=models.CharField(default='', max_length=142),
            preserve_default=False,
        ),
    ]
