# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0003_bioentry_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areabio',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
