# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0004_auto_20170218_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areabio',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='areabio',
            name='country',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='areabio',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
