# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0005_auto_20170218_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='areabio',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='areabio',
            name='age',
            field=models.IntegerField(null=True, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='areabio',
            name='country',
            field=models.CharField(max_length=150, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='areabio',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='areabio',
            name='name',
            field=models.CharField(max_length=150, null=True, verbose_name='Name'),
        ),
    ]
