# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0006_auto_20170218_1642'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='areabio',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='bioentry',
            name='description',
            field=models.CharField(blank=True, max_length=142, null=True, verbose_name='Reason'),
        ),
        migrations.AlterField(
            model_name='bioentry',
            name='living_space',
            field=models.IntegerField(verbose_name='Living space'),
        ),
        migrations.AlterField(
            model_name='bioentry',
            name='number_of_people',
            field=models.IntegerField(verbose_name='Number of people'),
        ),
        migrations.AlterField(
            model_name='bioentry',
            name='year_from',
            field=models.IntegerField(verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='bioentry',
            name='year_to',
            field=models.IntegerField(verbose_name='To'),
        ),
    ]
