# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0007_auto_20170221_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='areabio',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
