# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 09:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0008_areabio_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areabio',
            options={'ordering': ['-created'], 'verbose_name': 'Fl\xe4chenbiografie', 'verbose_name_plural': 'Fl\xe4chenbiografien'},
        ),
    ]
