# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0009_auto_20170320_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bioentry',
            name='description',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Reason'),
        ),
    ]
