# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0010_auto_20170417_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='areabio',
            name='mailed_to',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
