# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-11 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0011_areabio_mailed_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bioentry',
            name='description',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='Reason'),
        ),
    ]
