# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-12 22:43
from __future__ import unicode_literals

from django.db import migrations


def remove_countries(apps, schema_editor):
    AreaBio = apps.get_model("areas", "AreaBio")
    AreaBio.objects.update(country='Berlin')


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0012_auto_20170511_1944'),
    ]

    operations = [
        migrations.RunPython(remove_countries)
    ]
