# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-12 23:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0013_auto_20170513_0043'),
    ]

    operations = [
    ]
