# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-12 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0014_auto_20170513_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areabio',
            name='country',
            field=models.CharField(max_length=150, null=True, verbose_name='City'),
        ),
    ]
