# Generated by Django 6.0.1 on 2026-02-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0016_bioentry_housing_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areabio',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bioentry',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
