# Generated by Django 6.0.1 on 2026-02-16 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0018_areabio_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bioentry',
            options={'ordering': ['year_from'], 'verbose_name': 'Biografieeintrag', 'verbose_name_plural': 'Biografieeinträge'},
        ),
        migrations.AlterField(
            model_name='areabio',
            name='age',
            field=models.IntegerField(null=True, verbose_name='Alter'),
        ),
        migrations.AlterField(
            model_name='areabio',
            name='country',
            field=models.CharField(max_length=150, null=True, verbose_name='Stadt'),
        ),
        migrations.AlterField(
            model_name='areabio',
            name='mailed_to',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Per E-Mail versendet an'),
        ),
        migrations.AlterField(
            model_name='areabio',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Veröffentlicht'),
        ),
        migrations.AlterField(
            model_name='bioentry',
            name='description',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='Grund für den Wechsel'),
        ),
        migrations.AlterField(
            model_name='bioentry',
            name='living_space',
            field=models.IntegerField(verbose_name='Wohnfläche'),
        ),
        migrations.AlterField(
            model_name='bioentry',
            name='number_of_people',
            field=models.IntegerField(verbose_name='Personen im Haushalt'),
        ),
        migrations.AlterField(
            model_name='bioentry',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='PLZ'),
        ),
        migrations.AlterField(
            model_name='bioentry',
            name='year_from',
            field=models.IntegerField(verbose_name='Von'),
        ),
        migrations.AlterField(
            model_name='bioentry',
            name='year_to',
            field=models.IntegerField(verbose_name='Bis'),
        ),
    ]
