# Generated by Django 6.0.4 on 2026-04-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0019_alter_bioentry_options_alter_areabio_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areabio',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Erstellt'),
        ),
    ]
