# Generated by Django 6.0.4 on 2026-04-27 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0020_alter_areabio_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areabio',
            name='mailed_to',
        ),
        migrations.RemoveField(
            model_name='areabio',
            name='published',
        ),
    ]
