# Generated by Django 6.0.4 on 2026-04-27 15:48

from django.db import migrations, models
from django.utils import timezone


def set_birth_year(apps, schema_editor):
    AreaBio = apps.get_model('areas', 'AreaBio')
    current_year = timezone.localdate().year
    for bio in AreaBio.objects.exclude(age__isnull=True):
        bio.birth_year = current_year - bio.age
        bio.save(update_fields=['birth_year'])


def unset_birth_year(apps, schema_editor):
    AreaBio = apps.get_model('areas', 'AreaBio')
    AreaBio.objects.update(birth_year=None)


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0021_remove_areabio_mailed_to_remove_areabio_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='areabio',
            name='birth_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Geburtsjahr'),
        ),
        migrations.AlterField(
            model_name='areabio',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Alter'),
        ),
        migrations.RunPython(set_birth_year, unset_birth_year),
    ]
