# Generated by Django 6.0.4 on 2026-04-28 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0022_areabio_birth_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areabio',
            options={'ordering': ['-created'], 'verbose_name': 'Wohnbiografie', 'verbose_name_plural': 'Wohnbiografien'},
        ),
    ]
