# Generated by Django 6.0.4 on 2026-05-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0024_rename_year_fields_remove_birth_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bioentry',
            name='age_from',
            field=models.IntegerField(verbose_name='Von (Alter)'),
        ),
        migrations.AlterField(
            model_name='bioentry',
            name='age_to',
            field=models.IntegerField(verbose_name='Bis (Alter)'),
        ),
    ]
